Feat: 판매 상품 수정 구현
PhoenixFE/orum-market-front pull request #63
Opened 2023-12-12 07:35 UTC by veryyounng

## 🧾 관련 이슈
close : #23 

## 🔎 구현한 내용
상품 id 연결하기
 상품 데이터 조회
상품 설명 수정을 위해 editor 설치 후 구현
 데이터 수정 구현

## 📸 스크린샷(선택사항)

## 🙌 리뷰어에게
editor를 설치해서 npm i 하셔야 합니다.
상품 설명을 다 지우면 editor 까지 지워지는 이슈가 발생합니다.

2023-12-12 08:02 UTC, jingoworld requested changes
수고하셨습니다. 리뷰 남긴 부분들 수정 부탁드립니다.

2023-12-12 08:02 UTC, jingoworld commented on src/components/seller/ProductUpdate.tsx
> +};
반복되는 부분이니 따로 빼도 좋을 거 같아요.

2023-12-12 08:02 UTC, jingoworld commented on src/components/seller/ProductUpdate.tsx
>    };
라우터 돔에서 제공하는 기능이 있는 걸로 알고 있어요. 이거도 좋은데 간단한 거니, 검색해서 두 개 차이 알아보시고 더 나은 거 사용하면 될 거 같습니다.

2023-12-12 08:02 UTC, jingoworld commented on src/components/seller/ProductUpdate.tsx
> +          path: `https://localhost:443${response.data.file.path}`,
path는 상수로 관리하시는 게 나중에 수정하기 편리할 거에요. 나중에 하나씩 찾기도 힘드실 거구요. env에 통일된 규칙으로 지정하면 좋을 거 같습니다.

2023-12-12 08:02 UTC, jingoworld commented on src/components/seller/ProductUpdate.tsx
> +  };
테스트용 console.log는 최대한 삭제하고 PR 부탁드립니다.

2023-12-13 00:50 UTC, veryyounng commented on src/components/seller/ProductUpdate.tsx
> +};
넵

2023-12-13 00:50 UTC, veryyounng commented on src/components/seller/ProductUpdate.tsx
>    };
넵 감사합니다

2023-12-13 00:50 UTC, veryyounng commented on src/components/seller/ProductUpdate.tsx
> +          path: `https://localhost:443${response.data.file.path}`,
넵

2023-12-13 00:50 UTC, veryyounng commented on src/components/seller/ProductUpdate.tsx
> +  };
넵!

2023-12-13 05:30 UTC, jingoworld approved these changes
수고하셨습니다.

2023-12-14 09:23 UTC, merged