Feat: 판매 상품 관리 페이지 구현
PhoenixFE/orum-market-front pull request #85
Opened 2023-12-15 05:36 UTC by veryyounng

## 🧾 관련 이슈
close : 
#76 

## 🔎 구현한 내용
판매자 상품 리스트 조회

## 📸 스크린샷(선택사항)
![image](https://github.com/PhoenixFE/orum-market-front/assets/121228672/d5f4f8e5-5176-4aac-9179-3c2a63c904af)

## 🙌 리뷰어에게
액박으로 뜨는 파일은 제가 upload 폴더에서 삭제해서 그렇습니다.

2023-12-15 06:18 UTC, jingoworld reviewed
스크린샷 상에서는 주문상태가 안보이는데, 맞는건가요?

2023-12-19 07:18 UTC, wSeungMi commented on src/components/seller/SellerOrderList.tsx
> +  console.log('판매상품 리스트', productList);
다음 작업 하실 때 console.log 지워주세요~!

2023-12-19 07:19 UTC, veryyounng commented on src/components/seller/SellerOrderList.tsx
> +  console.log('판매상품 리스트', productList);
넵 잊지않겠습니다

2023-12-19 07:19 UTC, wSeungMi commented on src/components/seller/SellerOrderList.tsx
> +            console.log('orderItem', orderItem.state);
이 로그도 지워주세요!

2023-12-19 07:21 UTC, wSeungMi commented on src/components/seller/SellerOrderList.tsx
> +      case '최신순':
필터 부분은 useSort 커스텀훅이 있어서 그거 사용하면 좋을 것 같아요.

2023-12-19 07:22 UTC, wSeungMi approved these changes
말씀드린 부분은 계속 작업하시면서 반영하시면 좋을 것 같아요!
고생하셨습니다.

2023-12-19 07:24 UTC, veryyounng commented on src/components/seller/SellerOrderList.tsx
> +      case '최신순':
넵 감사합니다

2023-12-19 07:24 UTC, veryyounng commented on src/components/seller/SellerOrderList.tsx
> +            console.log('orderItem', orderItem.state);
넵

2023-12-19 08:49 UTC, jingoworld requested changes
![image](https://github.com/PhoenixFE/orum-market-front/assets/3222504/2484ea97-6906-455a-b6cf-6c66dacab107)

- [x] 사이드바와 본문 매칭이 안됩니다.
- [x] 수정, 삭제, 등록 버튼이 여기에 있어야 할텐데 주문 목록과 상품을 햇갈리셨나 봅니다.

파일 2개니까 잘 정리해주세요.

2023-12-19 08:49 UTC, jingoworld commented on src/components/seller/ProductManager.tsx
>    // 날짜 변환 함수
lib/formatDate.ts
가져다 쓰시면 됩니다.

2023-12-19 08:49 UTC, jingoworld commented on src/components/seller/SellerOrderList.tsx
> +  }
lib/formatDate.ts
가져다 쓰시면 됩니다.

2023-12-19 15:26 UTC, veryyounng commented on src/components/seller/ProductManager.tsx
>    // 날짜 변환 함수
넵 감사합니다

2023-12-19 15:26 UTC, veryyounng commented on src/components/seller/SellerOrderList.tsx
> +  }
넹

2023-12-19 15:34 UTC, jingoworld requested changes

2023-12-19 15:34 UTC, jingoworld commented on src/components/seller/SellerOrderManager.tsx
> +
함수 임포트

2023-12-19 15:34 UTC, jingoworld commented on src/components/seller/SellerOrderManager.tsx
> +  }, [productList, sortOrder]);
useSort 임포트

2023-12-19 15:34 UTC, jingoworld commented on src/components/seller/SellerOrderManager.tsx
> +                      alt="main-Image"
alt 설명이 다 같을 수 있으니 기왕 가져온 데이터 써도 좋을 거 같아요.
rows.mainImages[0].name

2023-12-19 15:34 UTC, jingoworld commented on src/components/seller/SellerOrderManager.tsx
> +                    <Link to={`http://localhost:5173/product/${rows._id}`}>
주소 부분 상수로 추출해서 관리하셔야 나중에 고생 안하십니다. 미리 작업해 두시는게 좋습니다.

2023-12-19 15:34 UTC, jingoworld commented on src/constants/index.ts
> +      title: '주문 상태 관리',
주문 관리' 는 어떤가요?
상태' 라는 단어는 프로그래밍에서 쓰이는 용어다보니 익숙해져 있는데 제가 쓰는 쇼핑몰은 단순하게 주문관리, 주문목록 이렇게만 써있어서 의견 내 봅니다.

2023-12-19 15:39 UTC, veryyounng commented on src/components/seller/SellerOrderManager.tsx
> +
넵

2023-12-19 16:14 UTC, veryyounng commented on src/constants/index.ts
> +      title: '주문 상태 관리',
넵

2023-12-19 16:14 UTC, veryyounng commented on src/components/seller/SellerOrderManager.tsx
> +                      alt="main-Image"
넵

2023-12-19 16:20 UTC, veryyounng commented on src/components/seller/SellerOrderManager.tsx
> +                    <Link to={`http://localhost:5173/product/${rows._id}`}>
네 !

2023-12-19 16:39 UTC, jingoworld approved these changes
수고하셨어요!

2023-12-19 16:47 UTC, merged